# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.lact.enable = true;
  hardware.amdgpu.overdrive.enable = true;

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.kernelPackages = pkgs.linuxPackages_6_12;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af06c418-2abc-42a9-b440-0c202327d872";
    fsType = "btrfs";
    options = ["subvol=root" "compress-force=zstd:15"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/af06c418-2abc-42a9-b440-0c202327d872";
    fsType = "btrfs";
    options = ["subvol=nix" "compress-force=zstd:15" "noatime"];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6e892922-165f-4ab7-9efc-65f1ab3005c3";
    fsType = "btrfs";
    options = ["subvol=hroot" "compress=zstd"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  system.stateVersion = "25.05"; # Did you read the comment?
}
